# Generated by Django 6.1.1 on 2026-09-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
