# Generated by Django 6.1.1 on 2026-10-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
